print('OI')
raise Exception("error esperado")